# Generated by Django 5.2.3 on 2025-06-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sportstournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('statdate', models.DateField()),
                ('enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchdate', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('tourid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportstournaments.sportstournaments')),
            ],
        ),
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('couch', models.CharField(max_length=200)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportstournaments.sportstournaments')),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=200)),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportstournaments.teams')),
            ],
        ),
        migrations.CreateModel(
            name='matchresults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamonescore', models.IntegerField()),
                ('teamtwoscore', models.IntegerField()),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportstournaments.matches')),
                ('winnerteamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportstournaments.teams')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='teamoneid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamone_matches', to='sportstournaments.teams'),
        ),
        migrations.AddField(
            model_name='matches',
            name='teamtwoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamtwo_matches', to='sportstournaments.teams'),
        ),
    ]
